.TH "AbstractControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractControl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AbstractControl\&.h>\fP
.PP
Inherited by \fBaddAccommodation\fP, \fBListHostAccommodationControl\fP, \fBLoginControl\fP, \fBLogoutControl\fP, \fBOpaqueInventoryControl\fP, \fBRegisterControl\fP, \fBSearchControl\fP, \fBSearchReservationControl\fP, \fBSessionControl\fP, and \fBWithdrawalControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractBoundary\fP * \fBgetBoundary\fP ()"
.br
.ti -1c
.RI "\fBMember\fP * \fBgetCurrentMember\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractControl\fP (\fBAbstractBoundary\fP *boundary)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Control 추상 클래스 

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
