.TH "AbstractBoundary" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractBoundary
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBaddAccommodationUI\fP, \fBListHostAccommodationUI\fP, \fBLoginUI\fP, \fBLogoutUI\fP, \fBOpaqueInventoryUI\fP, \fBRegisterUI\fP, \fBSearchReservationUI\fP, \fBSearchUI\fP, \fBSessionUI\fP, and \fBWithdrawalUI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBprint\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "virtual void \fBprintLine\fP (const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstractControl\fP * \fBgetControl\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAbstractControl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
