.TH "Accommodation" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Accommodation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccommodation\fP (string hostid, string name, string address, int cost, string date, int opaqueCost)"
.br
.ti -1c
.RI "const string & \fBgetHostid\fP () const"
.br
.ti -1c
.RI "void \fBsetHostid\fP (const string &hostid)"
.br
.ti -1c
.RI "const string & \fBgetName\fP () const"
.br
.ti -1c
.RI "void \fBsetName\fP (const string &name)"
.br
.ti -1c
.RI "const string & \fBgetAddress\fP () const"
.br
.ti -1c
.RI "void \fBsetAddress\fP (const string &address)"
.br
.ti -1c
.RI "int \fBgetCost\fP () const"
.br
.ti -1c
.RI "void \fBsetCost\fP (int cost)"
.br
.ti -1c
.RI "const string & \fBgetDate\fP () const"
.br
.ti -1c
.RI "void \fBsetDate\fP (const string &date)"
.br
.ti -1c
.RI "int \fBgetOpaqueCost\fP () const"
.br
.ti -1c
.RI "void \fBsetOpaqueCost\fP (int opaqueCost)"
.br
.ti -1c
.RI "const string & \fBgetCreateDate\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
