.TH "addAccommodation" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
addAccommodation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <addAccommodation\&.h>\fP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddNewAccommodation\fP (string hostid, string name, string address, int cost, string date, int opaqueCost)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
숙소 등록 Control 

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
