.TH "DateTimeUtils" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DateTimeUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBaddDays\fP (string time, int days)"
.br
.ti -1c
.RI "static string \fBaddYears\fP (string time, int years)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
