.TH "Guest" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Guest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMember\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGuest\fP (const string &name, const string &securityNumber, const string &address, const string &id, const string &password)"
.br
.ti -1c
.RI "const string \fBgetLastOpaqueTryTime\fP () const"
.br
.ti -1c
.RI "void \fBsetLastOpaqueTryTime\fP (const string &lastOpaqueTryTime)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
