.TH "Host" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Host
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMember\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHost\fP (const string &name, const string &securityNumber, const string &address, const string &id, const string &password)"
.br
.ti -1c
.RI "\fBAccommodationCollection\fP * \fBgetAccommodations\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
