.TH "ListHostAccommodationControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListHostAccommodationControl
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlistAccommodations\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
