.TH "LoginControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoginControl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LoginControl\&.h>\fP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtryLogin\fP (string id, string password)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
로그인 관련 Control 
.SH "Member Function Documentation"
.PP 
.SS "void LoginControl::tryLogin (string id, string password)"
Login을 시도 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP 
.br
\fIpassword\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
