.TH "LogoutControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogoutControl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LogoutControl\&.h>\fP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtryLogout\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
로그아웃 Control 
.SH "Member Function Documentation"
.PP 
.SS "void LogoutControl::tryLogout ()"
로그아웃을 시도함 

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
