.TH "OpaqueInventoryControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpaqueInventoryControl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpaqueInventoryControl\&.h>\fP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtryOpaqueInventoryReservation\fP (string address, string date, int opaqueCost)"
.br
.ti -1c
.RI "string \fBaddOpaqueReservation\fP (string hostid, string accommodation, int opaqueCost)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
OpaqueInventory 예약 시도 Control 
.SH "Member Function Documentation"
.PP 
.SS "void OpaqueInventoryControl::tryOpaqueInventoryReservation (string address, string date, int opaqueCost)"
OpaqueInventory 예약을 시도 
.PP
\fBParameters:\fP
.RS 4
\fIaddress\fP 
.br
\fIdate\fP 
.br
\fIopaqueCost\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
