.TH "OutputWriter" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutputWriter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OutputWriter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBopen\fP (string fileName)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (string fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBwriteLine\fP (string fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBwriteLine\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAbstractBoundary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
File Writing 과 관련된 Class 

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
