.TH "RegisterControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegisterControl
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBregisterMember\fP (MemberTypes type, string name, string securityNumber, string address, string id, string password)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void RegisterControl::registerMember (MemberTypes type, string name, string securityNumber, string address, string id, string password)"
회원등록 요청을 수행 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP 
.br
\fIname\fP 
.br
\fIsecurityNumber\fP 
.br
\fIaddress\fP 
.br
\fIid\fP 
.br
\fIpassword\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
