.TH "Reservation" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reservation
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReservation\fP (const string &hostid, const string &guestid, const string &name, const string &address, const string &date, int cost)"
.br
.ti -1c
.RI "const string & \fBgetGuestID\fP () const"
.br
.ti -1c
.RI "void \fBsetGuesid\fP (const string &guesid)"
.br
.ti -1c
.RI "const string & \fBgetHostID\fP () const"
.br
.ti -1c
.RI "void \fBsetHostid\fP (const string &hostid)"
.br
.ti -1c
.RI "const string & \fBgetName\fP () const"
.br
.ti -1c
.RI "void \fBsetName\fP (const string &name)"
.br
.ti -1c
.RI "const string & \fBgetAddress\fP () const"
.br
.ti -1c
.RI "void \fBsetAddress\fP (const string &address)"
.br
.ti -1c
.RI "const string & \fBgetDate\fP () const"
.br
.ti -1c
.RI "void \fBsetDate\fP (const string &date)"
.br
.ti -1c
.RI "int \fBgetCost\fP () const"
.br
.ti -1c
.RI "void \fBsetCost\fP (int cost)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
