.TH "SearchUI" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SearchUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractBoundary\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlistSearchResult\fP (string basic_string, string basicString)"
.br
.ti -1c
.RI "void \fBonReservateButtonClick\fP (string hostid, string guestid, string accommoname)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void SearchUI::listSearchResult (string basic_string, string basicString)"
검색 요청 
.PP
\fBParameters:\fP
.RS 4
\fIbasic_string\fP 
.br
\fIbasicString\fP 
.RE
.PP

.SS "void SearchUI::onReservateButtonClick (string hostid, string guestid, string accommoname)"
예약 시도 
.PP
\fBParameters:\fP
.RS 4
\fIhostid\fP 
.br
\fIguestid\fP 
.br
\fIaccommoname\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
