.TH "SearchControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SearchControl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SearchControl\&.h>\fP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsearchAccommodations\fP (string address, string date)"
.br
.ti -1c
.RI "void \fBaddReservation\fP (string hostid, string guestid, string accommoname)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
숙소 검색 + 예약 시도 

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
