.TH "SearchReservationControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SearchReservationControl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SearchReservationControl\&.h>\fP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSearchReservation\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
예약 내역 조회 
.SH "Member Function Documentation"
.PP 
.SS "void SearchReservationControl::SearchReservation ()"
현재 세션의 예약 내역을 list 

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
