.TH "SessionControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SessionControl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SessionControl\&.h>\fP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeSession\fP (string userID)"
.br
.ti -1c
.RI "void \fBchangeSessionToGuest\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
세션 관련 명령을 수행 
.SH "Member Function Documentation"
.PP 
.SS "void SessionControl::changeSession (string userID)"
세션 전환 
.PP
\fBParameters:\fP
.RS 4
\fIuserID\fP 
.RE
.PP

.SS "void SessionControl::changeSessionToGuest ()"
\fBGuest\fP 세션 전환 

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
