.TH "Session" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Session
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSession\fP ()"
.br
.ti -1c
.RI "\fBSession\fP (\fBMember\fP *member)"
.br
.ti -1c
.RI "bool \fBisGuest\fP ()"
.br
.ti -1c
.RI "\fBMember\fP * \fBgetMember\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Session::Session ()"
\fBGuest\fP 세션 생성자\&. 
.SS "Session::Session (\fBMember\fP * member)"
로그인 사용자 세션 
.PP
\fBParameters:\fP
.RS 4
\fImember\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
