.TH "WithdrawalControl" 3 "Wed May 30 2018" "sw_engineering_hw3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WithdrawalControl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WithdrawalControl\&.h>\fP
.PP
Inherits \fBAbstractControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdeleteMember\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
회원 탈퇴 Control 
.SH "Member Function Documentation"
.PP 
.SS "void WithdrawalControl::deleteMember ()"
회원 삭제 요청을 수행 

.SH "Author"
.PP 
Generated automatically by Doxygen for sw_engineering_hw3 from the source code\&.
