//
// Created by kimch on 2018-05-24.
//

#ifndef SW_ENGINEERING_HW3_MEMBERCOLLECTION_H
#define SW_ENGINEERING_HW3_MEMBERCOLLECTION_H


class MemberCollection {

};


#endif //SW_ENGINEERING_HW3_MEMBERCOLLECTION_H
